alias encrypt='gpg -c'
alias decrypt='gpg -d'
alias ls='ls -lah --color=auto'
alias grep='grep --color=auto'
alias archive='tar -czvf'
alias extract='tar -xzvf'
alias refresh='source ~/.bashrc'
alias diskspace='ncdu'

alias pkgi='sudo pacman -S'
alias pkgr='sudo pacman -R'
alias pkgu='sudo pacman -Syu'
alias pkgs='sudo pacman -Ss'
alias pkgf='echo "find installed package"'
